### ISSUE TITLE
Generate the whole bunch of mines after the first click?

### ISSUE THREAD

**Issue by emptymalei** [mondaychen/minesweeper#1]
Thx for this fun game. 

I found that sometimes i step on a mine exactly on my first click. As stated, I guess the mines should be placed after the first click.

Here is a screenshot.

![image](https://cloud.githubusercontent.com/assets/663798/6679790/fe6808a8-cc12-11e4-960b-d2263d77ce90.png)

**Comment by mondaychen** [comment]
Thanks for playing and good advise! I'll add the feature to avoid this case in the weekends.

**Comment by mondaychen** [comment]
fixed 50870bd8ad7bfabc6a614975199a52e3d937cd11
